:toc:

# FlatGov
Utilities and applications for the FlatGov project

## Data

### Bulk downloads

The core metadata that will be used for this project can be downloaded in bulk from ProPublica<sup>TM</sup> here: https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills

Bulk historical metadata is available for one-year ranges. Data for the current Congress is updated twice daily.

### Scraping
#### Install `unitedstates/congress` repository and dependencies

The text of bills can be scraped with the Python project here: `https://github.com/unitedstates/congress`. Install the `congress` Python virtual environment, install the requirements (`pip install requirements.txt`). The scrapers were built with Python 2.7 and have not been upgraded; updates may be needed for a production environment, but the `@unitedstates/congress` scraper is sufficient to gather the baseline data to test the utilities in this repository.

On MacOS (Catalina), installing the `congress` requirements involved a few adjustments:

1. Install OpenSSL 1.02 with Homebrew. The latest OpenSSL (>1.1) causes problems with certain requirements; unfortunately, version 1.0.0 also failed. A script was set up by a Github user to install version 1.0.2.

`brew uninstall openssl --ignore-dependencies; brew uninstall openssl --ignore-dependencies; brew uninstall libressl --ignore-dependencies; brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8b9d6d688f483a0f33fcfc93d433de501b9c3513/Formula/openssl.rb;`

2. Link the OpenSSL libraries

```
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
```

3. Install `pytz`, `pep517` and `cryptography` directly

```bash
pip install pytz
pip install pep517
pip install cryptography
```

4. Install requirements

From the `congress` repository directory, `pip install -r requirements.txt`

### Run the scraper

```bash
./run govinfo --bulkdata=BILLSTATUS
./run bills
```

When running initially, I got an error because the bulk directories had not been made. To unzip the files manually in all directories:

`find . -name "*.zip" | xargs -P 5 -I fileName sh -c 'unzip -o -d "$(dirname "fileName")/$(basename -s .zip "fileName")" "fileName"'`

## Metadata

Once the files are stored in the `congress/data` directory, a metadata file can be created with the following information: *Congress*, *Name*, *Path to XML or Text*, *Path to Metadata*, *Sponsors*. As an initial form, the metadata file will be:

billdata.json
```javascript
[ 
  116hr1ih: {
          name: '116hr1ih',
          sponsors: ['name1', 'name2'...],
          titles: [],
          titles_whole_bill: [],
          path_xml: '...',
          path_text: '...',
          path_metadata: '...,
           }
           ...
  115hjres31: {
     }
]
```

Where 'titles' includes all titles and 'full_titles' includes those where `"is_for_portion": false` (see below). 

### Cosponsors
This information is available 

### Bill Titles
This information is available for each bill (and version) in the `data.json` file. For example, in `/congress/data/116/bills/hr/hr3/data.json`. The title information is in the form:

```javascript
"titles": [
    {
      "as": "introduced", 
      "is_for_portion": false, 
      "title": "INVEST in America Act", 
      "type": "short"
    }, 
    {
      "as": "introduced", 
      "is_for_portion": false, 
      "title": "INVEST in America Act", 
      "type": "short"
    }, 
    {
      "as": "introduced", 
      "is_for_portion": false, 
      "title": "Investing in a New Vision for the Environment and Surface Transportation in America Act", 
      "type": "short"
    } ...
]
```

## Finding Related Bills

### Similarity calculation

For any bill (e.g. 116hr100ih), we want to find related bills for previous congresses. Related bills are listed for the same congress in Congress.gov, e.g. https://www.congress.gov/bill/116th-congress/house-bill/2/related-bills?q={"search":["hr2"]}&r=1&s=3.  There are many ways of calculating similarity. We will use an overall similarity measure, with a value between 0 and 1. The similarity is calculated as a linear combination of matching functions of the form:

`Similarity(bill~1~,bill~2~) = normalize(w~1~*f~1~(bill~1~, bill~2~) + w~2~*f~2~(bill1, bill2) + ...)`

NOTE: a bill text similarity engine is here https://github.com/govtrack/govtrack.us-web/blob/master/analysis/text_incorporation.py

Each similarity function has the following properties:

name:: a unique name for the feature being measured
function:: a function that takes in metadata or text from the two bills and returns a value between 0 and 1
minthreshold:: the minimum value of the function that will be counted; if the function value is less than minthreshold, it is set to 0
maxthreshold:: 
a threshold that sets the whole function to 'true'. If the function is greater than this value, the two bills are considered to be a match. For example, if the titles are identical, the two bills will be considered a match, regardless of the value of the other functions.

