:toc:

# FlatGov: A https://demandprogress.org[Demand Progress] Project 
Utilities and applications for the FlatGov project by Demand Progress

This repository contains:

* A web application showing information for a given bill (Django/Python)
* Utilities to scrape and process bill data (Python)

Both components are described below.

## Web Application

The FlatGov web application is built using the Django/Python web application framework. The application is contained in the `server_py` directory of this repository. It makes use of data that is processed using the scrapers and scripts described in the <<Data>> and <<Metadata>> sections below.

### Quickstart

#### Create directories and clone this directory

* Create a parent `FlatgovDir` and *within* that directory, clone this repository:

```bash
$ mkdir FlatgovDir
$ cd FlatgovDir
$ git clone https://github.com/aih/FlatGov.git
$ cd FlatGov
```

#### Install Python dependencies

Create a new Python virtual environment. You can use `venv`, `virtualenv` or preferably https://github.com/pyenv/pyenv-virtualenv[`pyenv virtualenv`], which requires installing https://github.com/pyenv/pyenv[pyenv] first).

If you don't have pyenv, try installing with homebrew
```bash
$ brew update
$ brew install pyenv
```

If you don't have pyenv-virtualenv, try installing with homebrew
```bash
$ brew install pyenv-virtualenv
```
Note: you may have to manually update `~/.bashrc` for virtual env commands to work

Create the environment (with pyenv virtualenv):
```bash
$ pyenv install 3.7
$ pyenv virtualenv 3.7 flatgov
```
Note: you may have to specify the patch version e.g. 3.7.9

Activate the environment
```bash
$ pyenv activate flatgov
```

Then load the `requirements.txt` into the virtual environment:

```bash
$ cd /path/to/FlatGov/server_py
$ pip install -r requirements.txt
```

```bash
$ cd /path/to/FlatGov/
$ pip install -r requirements.txt
```

The requirements for `flatgovtools` and `server_py` are separate. But for simplicity, it's best to load them both in a single virtual environment.

#### Create .env file 

Copy `server_py/flatgov/.env-sample` to `server_py/flatgov/.env`, and change the `SECRET_KEY` defined in that file.

#### Data: download and process

Use Django manage.py commands to download the data and populate the database: https://github.com/aih/FlatGov/blob/master/django_database.adoc

TODO: describe what data will be stored locally after setting up the scrapers and database from `django_database.adoc`

#### Run the Django application

Run the application from `server_py/flatgov` (within the Python virtual environment you created above):

```bash
$ cd server_py/flatgov
$ python manage.py runserver
```

This will serve the application on localhost:8000. Currently, there is no home page; only pages for individual bills, at, e.g.:
http://localhost:8000/bills/116hr1500

## Data Background

This repository contains scripts in the `/flatgovtools` directory that download and process bill data. The default location for the data is in the parent directory of this repository (`FlatgovDir`, described above).

### Bulk downloads: bill metadata

The core metadata that will be used for this project can be downloaded in bulk from ProPublica^TM^ here: + https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills

For example:
https://s3.amazonaws.com/pp-projects-static/congress/bills/116.zip?_ga=2.93052057.587919213.1601076458-407540952.1601076458 +
https://s3.amazonaws.com/pp-projects-static/congress/bills/115.zip?_ga=2.159617977.587919213.1601076458-407540952.1601076458 +
... +
https://s3.amazonaws.com/pp-projects-static/congress/bills/110.zip?_ga=2.159617977.587919213.1601076458-407540952.1601076458 +

Bulk historical metadata is available for one-year ranges. Data for the current Congress is updated twice daily. The metadata is sufficient to test many of the functions in this library. Bill text comparison requires bulk download or scraping of the text.

A script to download and organize these files is provided in `flatgovtools/bulk_downloads.sh`.

To start, it is sufficient to download a few recent congresses (e.g. `116, 115, 114, 113`). Unzip, and copy the deepest directory into a single hierarchy so that you have:

```bash
FlatGovDir
   |
   -congress
       |
       -data
          |
          -116
          -115
          -114
          -113
```
### Processing Metadata: Background

For each bill a metadata file is created in `congress/data/relatedbills` with the following form, combining data from the original data.json with additional information from other bills: 

116hr1ih.json
```javascript
{ 
  titles: [...], 
  titles_whole_bill: [...],
  cosponsors: ['name1', 'name2'...],
  related_bills: [],
  related: [
    {116s1356: {
      titles: [],
      sponsor: {},
      cosponsors: [],
      identifies_by: "CRS"
    }
    },

  ]

}
```

Where 'titles' includes all titles and 'full_titles' includes those where `"is_for_portion": false` (see below). 

### Cosponsors
This information is available for each bill in the `data.json` file. Two key fields in `sponsors` are `name` and `bioguide_id`

### Bill Titles
This information is available for each bill (and version) in the `data.json` file. For example, in `/congress/data/116/bills/hr/hr3/data.json`. After collecting titles for each bill, a reverse index can be created, with the title as key and an array of billnumbers as value. This will identify the bills across congresses that share identical titles.

The title information in `data.json` is of the form:

```javascript
"titles": [
    {
      "as": "introduced", 
      "is_for_portion": false, 
      "title": "INVEST in America Act", 
      "type": "short"
    }, 
    {
      "as": "introduced", 
      "is_for_portion": false, 
      "title": "INVEST in America Act", 
      "type": "short"
    }, 
    {
      "as": "introduced", 
      "is_for_portion": false, 
      "title": "Investing in a New Vision for the Environment and Surface Transportation in America Act", 
      "type": "short"
    } ...
]
```

## Finding Related Bills

### Similarity measures: simple
* Simple similarity measures are obtained using the relatedBills.py file which expands upon the functionality generated by the files: billdata.py and process_bill_meta.py. 
* relatedBills.py uses the getRelatedBills() as a higher order function containing several functions that obtain simple similarity measures.

A few 'simple' measures can be taken of similarity. Bills which share:

* Identical titles
* Very similar titles (e.g. all but the year)
* Identical sponsor lists
* Significant overlap in sponsors

This can be represented in a summary JSON of the form:
`relatedBills.json`

```javascript
  116s130: {
    same_titles: ['116hr201', ...]
  }
]
```

OR

```javascript
116s130: [
  { billCongressTypeNumber: '116hr201' 
    cosponsors: [bioguide_id1, bioguide_id2],
    titles: ['Shared Title 1', 'Shared Title 2', etc.]
    similar_title: ['Similar (nonidentical) Title 1', 'Similar (nonidentical) Title 2', etc.]
  }...
  ],

]
          
```

#### (Same)Titles
It does this by creating a billnumber index with the bill metadata, and any similarity measures will subsequently be attributed to its corresponding number in the index. For example, after the index is created,a “getSameTitles” function is run, which loops through the index and creates a list of titles for that billNumber. A bill number with more than one title would then indicate that the bill has more than one version of itself. Identical titles would indicate identical bills, with different bill numbers.

#### Cosponsors
(to do)

#### Similar Title
(to )do

### Similarity calculation

For any bill (e.g. 116hr100ih), we want to find related bills for previous congresses. Related bills are listed for the same congress in Congress.gov, e.g. https://www.congress.gov/bill/116th-congress/house-bill/2/related-bills?q={"search":["hr2"]}&r=1&s=3. There are many ways of calculating similarity. 

For purposes of efficiency and performance, we have developed a similarity measure that built on a search engine model. In particular, we build an index of document headers and sections in Elasticsearch. We then calculate the similarity between any input text and sections in the index using the ES/Lucene 'more like this' metric. We combine the section to section similarity scores to yield an overall bill similarity measure.  For more details, see https://github.com/aih/FlatGov/blob/master/server_py/flatgov/elasticsearch/README.adoc


NOTE: a comparable bill text similarity engine is here https://github.com/govtrack/govtrack.us-web/blob/master/analysis/text_incorporation.py


#### Download bills with the unitedstates/congress scraper

- run the commands
```bash
./run govinfo --bulkdata=BILLSTATUS --congress=117`
./run bills
```

#### Celery task to update bill downloads and data

Updates to the data are done through the Celery taskrunner (see https://docs.celeryproject.org/en/stable/getting-started/introduction.html). Details of the tasks in Flatgov are in CELERY.adoc

- activate the virtualenv and go to `(flatgov) ~/.../FlatGov/server_py/flatgov$`
```bash
$ pyenv activate flatgov
$ cd ~/.../FlatGov/server_py/flatgov 
```
- Run the Celery worker

`celery worker -Q bill -A flatgov.celery:app -n flatgov.%%h --loglevel=info`

- Set up Celery schedule
`celery beat -S redbeat.RedBeatScheduler -A flatgov.celery:app --loglevel=info`


## Statement of Administration Policy

The metadata for Statement of Administration Policy section has been scraped and stored in json files. The pdfs are stored in the media directory.

### Load Policy Data for Obama Administration to Database

- activate the virtualenv and go to `(flatgov) ~/.../FlatGov/server_py$`
```bash

$ cd ~/.../FlatGov/server_py
$ source .venv/bin/activate

```

- Go to `(flatgov) ~/.../FlatGov/server_py/flatgov$`

```bash

$ cd flatgov

```

- Apply all migrations

```bash

./manage.py makemigrations
./manage.py migrate

```

- Load Statement of Administration Policy data

```bash

./manage.py loaddata dumped_statements.json 

```
