# Generated by Django 3.1.8 on 2021-06-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210608_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='committee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subcommittee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
