# Generated by Django 3.1.8 on 2021-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(null=True, upload_to='crs')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
