# Generated by Django 3.1.8 on 2021-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0002_csvreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvreport',
            name='file',
            field=models.FileField(null=True, upload_to='crs/'),
        ),
    ]
