# Generated by Django 3.1.8 on 2021-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0004_csvreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvreport',
            name='log',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
