# Generated by Django 3.1.6 on 2021-02-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('titles', models.TextField()),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
