# Generated by Django 3.1 on 2021-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', 'committeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='belongs_to',
            field=models.CharField(default='common', max_length=100),
        ),
    ]
