# Generated by Django 3.1 on 2021-02-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('titles', models.JSONField(default=list)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('thomas_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cosponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bioguide_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'bioguide_id')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_congress_type_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('congress', models.IntegerField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('titles', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('titles_whole_bill', models.JSONField(default=list)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('sponsor', models.JSONField(default=dict)),
                ('related_bills', models.JSONField(default=list)),
                ('related_dict', models.JSONField(default=dict)),
                ('cosponsors_dict', models.JSONField(default=list)),
                ('es_similarity', models.JSONField(default=list)),
                ('es_similar_bills_dict', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cosponsors', models.ManyToManyField(blank=True, related_name='cosponsors', to='bills.Cosponsor')),
            ],
        ),
    ]
