# Generated by Django 3.1.12 on 2021-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='es_similar_bills_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
