# Generated by Django 3.1.8 on 2021-04-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='committees_dict',
            field=models.JSONField(default=list),
        ),
    ]
