# Generated by Django 3.1 on 2021-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_auto_20210310_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='CboReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=1000)),
                ('original_pdf_link', models.CharField(max_length=255)),
                ('congress', models.CharField(max_length=55)),
                ('bill_number', models.CharField(max_length=127)),
                ('bill_id', models.CharField(blank=True, max_length=127, null=True)),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
