# Generated by Django 3.1 on 2020-11-13 14:49

from django.db import migrations, models


def forwards(apps, schema_editor):
    Bill = apps.get_model("bills", "Bill")
    db_alias = schema_editor.connection.alias
    bills = Bill.objects.all()
    for bill in bills.iterator():
        bill.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='titles_whole_bill',
            field=models.JSONField(default=list),
        ),
    ]
