# Generated by Django 3.1 on 2021-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=500)),
                ('title', models.TextField()),
                ('statement_type', models.CharField(max_length=500)),
                ('member_id', models.CharField(max_length=500)),
                ('congress', models.CharField(max_length=127)),
                ('member_uri', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=127)),
                ('chamber', models.CharField(max_length=127)),
                ('state', models.CharField(max_length=127)),
                ('party', models.CharField(max_length=127)),
                ('bill_number', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='statement',
            name='administration',
            field=models.CharField(default='common', max_length=100),
        ),
    ]
