# Generated by Django 3.1.8 on 2021-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosponsor',
            name='leadership',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
