# Generated by Django 3.1 on 2021-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210325_1832'),
    ]

    operations = [

    ]
