# Generated by Django 3.1.12 on 2021-08-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_cosponsor_leadership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PressStatement',
        ),
        migrations.DeleteModel(
            name='PressStatementTask',
        ),
        migrations.AddField(
            model_name='bill',
            name='isEnacted',
            field=models.BooleanField(default=False),
        ),
    ]
