# Generated by Django 3.1.12 on 2021-08-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_cosponsor_leadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='became_law',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
