# Generated by Django 3.1 on 2021-03-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_cboreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='belongs_to',
            new_name='administration',
        ),
    ]
