# Generated by Django 3.1.12 on 2021-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210819_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='permanent_pdf_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
