# Generated by Django 3.1 on 2020-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20201113_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='related_bills',
        ),
        migrations.AddField(
            model_name='bill',
            name='related_bills',
            field=models.ManyToManyField(blank=True, related_name='_bill_related_bills_+', to='bills.Bill'),
        ),
    ]
