# Generated by Django 3.1.8 on 2021-05-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_cosponsor_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='similar_top',
            field=models.JSONField(default=list),
        ),
    ]
