# Generated by Django 3.1.12 on 2021-08-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20210806_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='committees_dict',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cosponsors_dict',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='es_similar_bills_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bill',
            name='es_similarity',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='related_bills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
