# Generated by Django 3.1 on 2021-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_cboreport_committeedocument'),
    ]

    operations = [
    ]
