# Generated by Django 3.1 on 2021-03-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20210325_1916'),
    ]

    operations = [

    ]
