# Generated by Django 3.1 on 2020-11-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20201116_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='district',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='thomas_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='titles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sponsor',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Cosponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bioguide_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'bioguide_id')},
            },
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='bioguide_id',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='updated',
        ),
    ]
