# Generated by Django 3.1 on 2020-11-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20201116_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='title',
            new_name='titles',
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.sponsor'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cosponsors',
            field=models.ManyToManyField(blank=True, related_name='cosponsors', to='bills.Cosponsor'),
        ),
    ]
