# Generated by Django 3.1 on 2021-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_cboreport_committeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressStatementTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.CharField(max_length=127)),
                ('bill_number', models.CharField(max_length=127)),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], db_index=True, default='PENDING', help_text='Current state of the press statement task.', max_length=50, verbose_name='Task State')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
