# Generated by Django 3.1 on 2020-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20201116_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsor',
            field=models.JSONField(default=dict),
        ),
    ]
