# Generated by Django 3.1 on 2021-03-25 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_cboreport_committeedocument_pressstatementtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressstatementtask',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pressstatementtask',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
