# Generated by Django 3.1 on 2021-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20210325_1945'),
    ]

    operations = [
    ]
