# Generated by Django 3.1 on 2020-11-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20201116_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cosponsors_dict',
            field=models.JSONField(default=list),
        ),
    ]
