# Generated by Django 3.1 on 2021-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20210326_1944'),
    ]

    operations = [

    ]
