# Generated by Django 3.1 on 2020-11-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_bill_cosponsors_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_congress_type_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
