# Generated by Django 3.1 on 2021-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_cboreport_committeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressstatement',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
    ]
