# Generated by Django 3.1 on 2020-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_auto_20201118_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='titles_year',
            field=models.JSONField(default=list),
        ),
    ]
