# Generated by Django 3.1 on 2020-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_bill_titles_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='titles_year',
        ),
        migrations.AddField(
            model_name='bill',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
