# Generated by Django 3.1 on 2021-03-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_auto_20210326_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressstatement',
            name='is_scraped',
        ),
    ]
