# Generated by Django 3.1 on 2020-11-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_auto_20201118_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
