# Generated by Django 3.1 on 2021-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_auto_20210326_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressstatement',
            name='chamber',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='pressstatement',
            name='name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='pressstatement',
            name='party',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='pressstatement',
            name='state',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
