# Generated by Django 3.1 on 2020-11-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='congress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
