# Generated by Django 3.1 on 2020-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_bill_congress'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
