# Generated by Django 3.1 on 2020-11-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_bill_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='related_dict',
            field=models.JSONField(default=dict),
        ),
    ]
