# Generated by Django 3.1 on 2021-02-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0017_bill_es_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=127)),
                ('bill_id', models.CharField(blank=True, max_length=127, null=True)),
                ('bill_title', models.CharField(max_length=250)),
                ('congress', models.CharField(max_length=10)),
                ('date_issued', models.CharField(max_length=35)),
                ('permanent_pdf_link', models.FileField(blank=True, null=True, upload_to='statements/')),
                ('original_pdf_link', models.CharField(blank=True, max_length=255, null=True)),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
