# Generated by Django 3.1 on 2021-02-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_billupdatejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='es_similar_bills_dict',
            field=models.JSONField(default=dict),
        ),
    ]
