# Generated by Django 3.1 on 2021-01-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_billupdatejob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillUpdateJob',
        ),
    ]
