# Generated by Django 3.1 on 2021-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_statement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillUpdateJob',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='bill',
            new_name='bill_title',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='created_at',
            new_name='date_fetched',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='link',
            new_name='original_pdf_link',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='pdf_link',
        ),
        migrations.AddField(
            model_name='statement',
            name='bill_id',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='permanent_pdf_link',
            field=models.FileField(blank=True, null=True, upload_to='statements/'),
        ),
    ]
