# Generated by Django 3.1 on 2021-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_auto_20210202_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='bills',
            field=models.ManyToManyField(blank=True, to='bills.Bill'),
        ),
    ]
