# Generated by Django 3.1 on 2021-03-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('bill_number', models.CharField(blank=True, max_length=127, null=True)),
                ('chamber', models.CharField(blank=True, max_length=127, null=True)),
                ('category', models.CharField(max_length=127)),
                ('committee', models.CharField(max_length=500)),
                ('report_number', models.CharField(max_length=500)),
                ('associated_legislation', models.CharField(max_length=500)),
                ('original_pdf_link', models.CharField(max_length=500)),
                ('report_type', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('congress', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
    ]
