# Generated by Django 3.1 on 2021-01-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uscongress', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillUpdateJob',
            new_name='UscongressUpdateJob',
        ),
    ]
