# Generated by Django 3.1 on 2021-01-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscongress', '0003_auto_20210112_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uscongressupdatejob',
            old_name='status',
            new_name='fdsys_status',
        ),
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='bill_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='data_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='meta_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='related_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
