# Generated by Django 3.1 on 2021-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscongress', '0005_auto_20210112_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uscongressupdatejob',
            name='bill_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
