# Generated by Django 3.1 on 2021-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscongress', '0006_auto_20210112_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uscongressupdatejob',
            name='bill_list',
        ),
        migrations.RemoveField(
            model_name='uscongressupdatejob',
            name='data_content',
        ),
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='saved',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='skipped',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
