# Generated by Django 3.1 on 2021-01-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscongress', '0008_auto_20210112_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='elastic_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uscongressupdatejob',
            name='similarity',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
